project:
  type: website
  output-dir: docs

website:
  title: "Ryan McManus"
  favicon: "images/profile.png"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
      - text: Blog
        href: blog.qmd
      - text: WEI Map
        href: https://ryanmcmanus916.github.io/leaflet-maps-with-google-sheets/
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/ryan-mcmanus-energy
format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    code-link: true
    code-fold: show
    code-tools: false
    css: styles.css

editor: visual

